CREATE DATABASE UAE_RESTAURANT_DB;
USE DATABASE UAE_RESTAURANT_DB;
CREATE SCHEMA RESTAURANT_ANALYTICS;
USE SCHEMA RESTAURANT_ANALYTICS;

CREATE WAREHOUSE UAE_RESTAURANT_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE UAE_RESTAURANT_WH;

USE DATABASE UAE_RESTAURANT_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS CLEAN;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;


create or replace schema UAE_RESTAURANT_DB.RESTAURANT_ANALYTICS;

create or replace TABLE UAE_RESTAURANT_DB.RESTAURANT_ANALYTICS.BRANCHES (
	BRANCH_ID VARCHAR(16777216),
	BRANCH_NAME VARCHAR(16777216),
	EMIRATE VARCHAR(16777216),
	AREA VARCHAR(16777216),
	CONCEPT VARCHAR(16777216),
	SEATS NUMBER(38,0),
	HAS_DRIVE_THRU BOOLEAN,
	OFFERS_DELIVERY BOOLEAN,
	OPENED_DATE VARCHAR(16777216),
	MONTHLY_RENT_AED NUMBER(38,0)
);
create or replace TABLE UAE_RESTAURANT_DB.RESTAURANT_ANALYTICS.CHANNEL_DAILY (
	CHANNEL_SALES_ID VARCHAR(16777216),
	BRANCH_ID VARCHAR(16777216),
	BUSINESS_DATE VARCHAR(16777216),
	BUSINESS_MONTH VARCHAR(16777216),
	DAY_OF_WEEK VARCHAR(16777216),
	IS_WEEKEND BOOLEAN,
	ORDER_CHANNEL VARCHAR(16777216),
	ORDERS_COUNT NUMBER(38,0),
	COVERS NUMBER(38,0),
	GROSS_SALES_AED FLOAT,
	DISCOUNTS_AED FLOAT,
	NET_SALES_AED FLOAT,
	SERVICE_CHARGE_AED FLOAT,
	VAT_AED FLOAT,
	TOTAL_BILLED_AED FLOAT,
	AGGREGATOR_COMMISSION_AED FLOAT,
	NET_REVENUE_AED FLOAT,
	FOOD_COST_AED FLOAT,
	AVG_PREP_MINUTES FLOAT,
	AVG_REVIEW_SCORE FLOAT,
	CURRENCY VARCHAR(16777216)
);
create or replace TABLE UAE_RESTAURANT_DB.RESTAURANT_ANALYTICS.DAILY_OPERATIONS (
	SUMMARY_ID VARCHAR(16777216),
	BRANCH_ID VARCHAR(16777216),
	BUSINESS_DATE VARCHAR(16777216),
	BUSINESS_MONTH VARCHAR(16777216),
	DAY_OF_WEEK VARCHAR(16777216),
	IS_WEEKEND BOOLEAN,
	ORDERS_COUNT NUMBER(38,0),
	COVERS NUMBER(38,0),
	NET_SALES_AED FLOAT,
	DISCOUNTS_AED FLOAT,
	AGGREGATOR_COMMISSION_AED FLOAT,
	NET_REVENUE_AED FLOAT,
	FOOD_COST_AED FLOAT,
	WASTE_COST_AED FLOAT,
	LABOUR_HOURS FLOAT,
	LABOUR_COST_AED FLOAT,
	PRIME_COST_PCT FLOAT,
	AVG_REVIEW_SCORE FLOAT,
	CURRENCY VARCHAR(16777216)
);
create or replace TABLE UAE_RESTAURANT_DB.RESTAURANT_ANALYTICS.ITEM_MONTHLY_SALES (
	ITEM_SALES_ID VARCHAR(16777216),
	BRANCH_ID VARCHAR(16777216),
	BUSINESS_MONTH VARCHAR(16777216),
	ITEM_ID VARCHAR(16777216),
	MENU_CATEGORY VARCHAR(16777216),
	QUANTITY_SOLD NUMBER(38,0),
	GROSS_SALES_AED FLOAT,
	FOOD_COST_AED FLOAT,
	GROSS_MARGIN_AED FLOAT,
	CURRENCY VARCHAR(16777216)
);
create or replace TABLE UAE_RESTAURANT_DB.RESTAURANT_ANALYTICS.MENU_ITEMS (
	ITEM_ID VARCHAR(16777216),
	ITEM_NAME VARCHAR(16777216),
	MENU_CATEGORY VARCHAR(16777216),
	MENU_PRICE_AED FLOAT,
	ITEM_COST_AED FLOAT,
	PREP_MINUTES NUMBER(38,0),
	IS_VEGETARIAN BOOLEAN,
	CALORIES NUMBER(38,0),
	IS_ACTIVE BOOLEAN,
	LAUNCHED_DATE VARCHAR(16777216)
);




''' CHECKING DUPLICATES'''

SELECT m.item_id ,COUNT(*) AS Count__ FROM menu_items as m 
GROUP BY M.ITEM_ID
HAVING COUNT(*)>1;


SELECT B.BRANCH_ID,COUNT(*) AS Count_ FROM branches AS B
GROUP BY B.BRANCH_ID
HAVING COUNT(*)>1;

SELECT OP.SUMMARY_ID,COUNT(*) AS Count_ FROM daily_operations as OP
GROUP BY OP.SUMMARY_ID
HAVING COUNT(*)>1;

SELECT C.CHANNEL_SALES_ID,COUNT(*) AS Count_ FROM CHANNEL_DAILY AS C
GROUP BY C.CHANNEL_SALES_ID
HAVING COUNT(*)>1;

SELECT I.ITEM_SALES_ID,COUNT(*) AS Count_ FROM ITEM_MONTHLY_SALES AS I
GROUP BY I.ITEM_SALES_ID
HAVING COUNT(*)>1;

'''Duplicates - There are no duplicates in the data'''

'''CHECK NULL VALUES'''

SELECT Count(*) AS Total_rows,
    COUNT_IF(D.SUMMARY_ID IS NULL) AS null_summary_id,
    COUNT_IF(D.branch_id IS NULL) AS null_branch_id,
    COUNT_IF(D.business_date IS NULL) AS null_business_date,
    COUNT_IF(D.business_month IS NULL) AS null_business_month,
    COUNT_IF(D.day_of_week IS NULL) AS null_day_of_week,
    COUNT_IF(D.is_weekend IS NULL) AS null_is_weekend,
    COUNT_IF(D.orders_count IS NULL) AS null_orders_count,
    COUNT_IF(D.covers IS NULL) AS null_covers,
    COUNT_IF(D.net_sales_aed IS NULL) AS null_net_sales_aed,
    COUNT_IF(D.discounts_aed IS NULL) AS null_discounts_aed,
    COUNT_IF(D.net_revenue_aed IS NULL) AS null_net_revenue_aed,
    COUNT_IF(D.aggregator_commission_aed IS NULL) AS null_aggregator_commission_aed,
    COUNT_IF(D.food_cost_aed IS NULL) AS null_food_cost_aed,
    COUNT_IF(D.waste_cost_aed IS NULL) AS null_summary_id,
    COUNT_IF(D.labour_hours IS NULL) AS null_labour_hours,
    COUNT_IF(D.labour_cost_aed IS NULL) AS null_labour_cost_aed,
    COUNT_IF(D.prime_cost_pct IS NULL) AS null_prime_cost_pct,
    COUNT_IF(D.avg_review_score IS NULL) AS avg_review_score,
    COUNT_IF(D.currency IS NULL) AS null_currency
FROM DAILY_OPERATIONS AS D;


SELECT COUNT(*) AS Total_rows,
    COUNT_IF(I.ITEM_SALES_ID IS NULL) AS null_ITEM_SALES_ID,
    COUNT_IF(I.BRANCH_ID IS NULL) AS null_BRANCH_ID,
    COUNT_IF(I.BUSINESS_MONTH IS NULL) AS null_BUSINESS_MONTH,
    COUNT_IF(I.ITEM_ID IS NULL) AS null_ITEM_ID,
    COUNT_IF(I.MENU_CATEGORY IS NULL) AS null_MENU_CATEGORY,
    COUNT_IF(I.QUANTITY_SOLD IS NULL) AS null_QUANTITY_SOLD,
    COUNT_IF(I.GROSS_SALES_AED IS NULL) AS null_GROSS_SALES_AED,
    COUNT_IF(I.FOOD_COST_AED IS NULL) AS null_FOOD_COST_AED,
    COUNT_IF(I.GROSS_MARGIN_AED IS NULL) AS null_GROSS_MARGIN_AED,
    COUNT_IF(I.CURRENCY IS NULL) AS null_CURRENCY
FROM ITEM_MONTHLY_SALES AS I;


SELECT COUNT(*) AS Total_rows,
    COUNT_IF(C.CHANNEL_SALES_ID IS NULL) AS null_CHANNEL_SALES_ID,
    COUNT_IF(C.BRANCH_ID IS NULL) AS BRANCH_ID,
    COUNT_IF(C.BUSINESS_DATE IS NULL) AS BUSINESS_DATE,
    COUNT_IF(C.BUSINESS_MONTH IS NULL) AS BUSINESS_MONTH,
    COUNT_IF(C.DAY_OF_WEEK IS NULL) AS DAY_OF_WEEK,
    COUNT_IF(C.IS_WEEKEND IS NULL) AS IS_WEEKEND,
    COUNT_IF(C.ORDER_CHANNEL IS NULL) AS ORDER_CHANNEL,
    COUNT_IF(C.ORDERS_COUNT IS NULL) AS ORDERS_COUNT,
    COUNT_IF(C.COVERS IS NULL) AS COVERS,
    COUNT_IF(C.GROSS_SALES_AED IS NULL) AS GROSS_SALES_AED,
    COUNT_IF(C.DISCOUNTS_AED IS NULL) AS DISCOUNTS_AED,
    COUNT_IF(C.NET_SALES_AED IS NULL) AS NET_SALES_AED,
    COUNT_IF(C.SERVICE_CHARGE_AED IS NULL) AS SERVICE_CHARGE_AED,
    COUNT_IF(C.VAT_AED IS NULL) AS VAT_AED,
    COUNT_IF(C.TOTAL_BILLED_AED IS NULL) AS TOTAL_BILLED_AED,
    COUNT_IF(C.AGGREGATOR_COMMISSION_AED IS NULL) AS AGGREGATOR_COMMISSION_AED,
    COUNT_IF(C.NET_REVENUE_AED IS NULL) AS NET_REVENUE_AED,
    COUNT_IF(C.FOOD_COST_AED IS NULL) AS FOOD_COST_AED,
    COUNT_IF(C.AVG_PREP_MINUTES IS NULL) AS AVG_PREP_MINUTES,
    COUNT_IF(C.AVG_REVIEW_SCORE IS NULL) AS AVG_REVIEW_SCORE,
    COUNT_IF(C.CURRENCY IS NULL) AS CURRENCY
FROM CHANNEL_DAILY AS C;


SELECT COUNT(*) AS Total_rows,
    COUNT_IF(M.ITEM_ID IS NULL) AS Item_id,
    COUNT_IF(M.item_name IS NULL) AS item_name,
    COUNT_IF(M.menu_category IS NULL) AS menu_category,
    COUNT_IF(M.menu_price_aed IS NULL) AS menu_price_aed,
    COUNT_IF(M.item_cost_aed IS NULL) AS item_cost_aed,
    COUNT_IF(M.prep_minutes IS NULL) AS prep_minutes,
    COUNT_IF(M.is_vegetarian IS NULL) AS is_vegetarian,
    COUNT_IF(M.calories IS NULL) AS calories,
    COUNT_IF(M.is_active IS NULL) AS is_active,
    COUNT_IF(M.launched_date IS NULL) AS launched_date
FROM MENU_ITEMS AS M


SELECT COUNT(*) AS Total_rows,
    COUNT_IF(B.branch_id IS NULL) AS branch_id,
    COUNT_IF(B.BRANCH_NAME IS NULL) AS BRANCH_NAME,
    COUNT_IF(B.EMIRATE IS NULL) AS EMIRATE,
    COUNT_IF(B.AREA IS NULL) AS AREA,
    COUNT_IF(B.CONCEPT IS NULL) AS CONCEPT,
    COUNT_IF(B.SEATS IS NULL) AS SEATS,
    COUNT_IF(B.HAS_DRIVE_THRU IS NULL) AS HAS_DRIVE_THRU,
    COUNT_IF(B.OFFERS_DELIVERY IS NULL) AS OFFERS_DELIVERY,
    COUNT_IF(B.OPENED_DATE IS NULL) AS OPENED_DATE,
    COUNT_IF(B.MONTHLY_RENT_AED IS NULL) AS MONTHLY_RENT_AED,
FROM BRANCHES AS B;

''' There are no null values present in the dataset'''

'''Data quality checks'''
'''CHECK TEXT CONSISTENCY'''

SELECT DISTINCT EMIRATE FROM BRANCHES
ORDER BY EMIRATE;

SELECT DISTINCT OPENED_DATE FROM BRANCHES
ORDER BY OPENED_DATE;

SELECT * FROM BRANCHES
where seats < 0 OR MONTHLY_RENT_AED < 0


SELECT  OPENED_DATE,
    TRY_TO_DATE(OPENED_DATE,'DD-MM-YYYY') AS OPENED_DATE_NEW
FROM BRANCHES;



SELECT * FROM BRANCHES
LIMIT 1;
SELECT * FROM DAILY_OPERATIONS
LIMIT 1;
SELECT * FROM ITEM_MONTHLY_SALES
LIMIT 1;
SELECT * FROM MENU_ITEMS
LIMIT 1;
SELECT * FROM CHANNEL_DAILY
LIMIT 1;

'''Analysis 1 — Overall business KPIs'''

SELECT 
    COUNT(DISTINCT ORDER_CHANNEL) AS Total_order_channel,
    SUM(ORDERS_COUNT) AS TOTAL_ORDERS,
    SUM(COVERS) AS TOTAL_CUSTOMERS,
    SUM(GROSS_SALES_AED) AS GROSS_SALES, 
    SUM(NET_SALES_AED) AS NET_SALES, 
    SUM(DISCOUNTS_AED) AS DISCOUNT, 
    SUM(NET_REVENUE_AED) AS NET_REVENUE,
    SUM(AGGREGATOR_COMMISSION_AED) AS COMMISSION,
    SUM(SERVICE_CHARGE_AED) AS TOTAL_SERVICE_CHARGE,
    SUM(VAT_AED) AS TOTAL_VAT,
    SUM(FOOD_COST_AED) AS TOTAL_FOOD_cOST,
    ROUND(AVG(AVG_PREP_MINUTES),2) AS AVG_PREP_MINUTE,
    ROUND(AVG(AVG_REVIEW_SCORE),2) AS AVG_RATING,
    ROUND(SUM(NET_REVENUE_AED)/SUM(ORDERS_COUNT),2) AS AOV,
    ROUND(SUM(FOOD_COST_AED)/SUM(NET_REVENUE_AED)*100,2) AS FOOD_COST_PCT,
    ROUND(SUM(AGGREGATOR_COMMISSION_AED)/SUM(GROSS_SALES_AED) *100,2) AS COMMISION_PCT,
    SUM(NET_REVENUE_AED) - SUM(FOOD_COST_AED) AS GROSS_MARGIN,
    ROUND((SUM(NET_REVENUE_AED) - SUM(FOOD_COST_AED))/SUM(NET_REVENUE_AED) *100,2) AS GROSS_MARGIN_PCT
    
FROM CHANNEL_DAILY;

'''Monthly orders KPI'''

SELECT 
    BUSINESS_MONTH,
    COUNT(DISTINCT ORDER_CHANNEL) AS Total_order_channel,
    SUM(ORDERS_COUNT) AS TOTAL_ORDERS,
    LAG(SUM(ORDERS_COUNT)) OVER(ORDER BY BUSINESS_MONTH) AS PREV_MONTH_ORDER,
    ROUND((SUM(ORDERS_COUNT) - LAG(SUM(ORDERS_COUNT)) OVER(ORDER BY BUSINESS_MONTH))/LAG(SUM(ORDERS_COUNT)) OVER(ORDER BY BUSINESS_MONTH) *100,2) AS         MOM_ORDER_GROWTH_PCT,
    SUM(COVERS) AS TOTAL_CUSTOMERS,
    LAG(SUM(COVERS)) OVER(ORDER BY BUSINESS_MONTH) AS Prev_month_cust,
    ROUND((SUM(COVERS)- LAG(SUM(COVERS)) OVER(ORDER BY BUSINESS_MONTH))/LAG(SUM(COVERS)) OVER(ORDER BY BUSINESS_MONTH) *100,2) AS MOM_CUST_GROWTH_PCT,
    SUM(GROSS_SALES_AED) AS GROSS_SALES, 
    SUM(NET_SALES_AED) AS NET_SALES, 
    SUM(DISCOUNTS_AED) AS DISCOUNT, 
    SUM(NET_REVENUE_AED) AS NET_REVENUE,
    LAG(SUM(NET_REVENUE_AED)) OVER(ORDER BY BUSINESS_MONTH) AS Prev_month_NET_REVENUE,
    ROUND((SUM(NET_REVENUE_AED)-LAG(SUM(NET_REVENUE_AED)) OVER(ORDER BY BUSINESS_MONTH))/LAG(SUM(NET_REVENUE_AED)) OVER(ORDER BY BUSINESS_MONTH) * 100,2) AS MOM_REVENUE_GROWTH_PCT,
    SUM(AGGREGATOR_COMMISSION_AED) AS COMMISSION,
    SUM(SERVICE_CHARGE_AED) AS TOTAL_SERVICE_CHARGE,
    SUM(VAT_AED) AS TOTAL_VAT,
    SUM(FOOD_COST_AED) AS TOTAL_FOOD_cOST,
    AVG(AVG_PREP_MINUTES) AS AVG_PREP_MINUTE,
    AVG(AVG_REVIEW_SCORE) AS AVG_RATING,
    SUM(FOOD_COST_AED) AS MONTHLY_FOOD_COST,
    SUM(DISCOUNTS_AED) AS MONTHLY_DISCOUNTS,
    SUM(NET_REVENUE_AED)/SUM(ORDERS_COUNT) AS MONTHLY_AOV,
    LAG(SUM(NET_REVENUE_AED)/SUM(ORDERS_COUNT)) OVER(ORDER BY BUSINESS_MONTH) AS PREV_MONTH_AOV,
    ROUND(
    ((SUM(NET_REVENUE_AED)/SUM(ORDERS_COUNT))-
    (LAG(SUM(NET_REVENUE_AED)/SUM(ORDERS_COUNT)) OVER(ORDER BY BUSINESS_MONTH)))/
    (LAG(SUM(NET_REVENUE_AED)/SUM(ORDERS_COUNT)) OVER(ORDER BY BUSINESS_MONTH)) * 100,2) MOM_AOV_GROWTH_PCT
FROM CHANNEL_DAILY
GROUP BY BUSINESS_MONTH
ORDER BY BUSINESS_MONTH;



'''CHANNEL WISE KPI'''

SELECT 
    ORDER_CHANNEL,
    SUM(ORDERS_COUNT) AS TOTAL_ORDERS,
    SUM(COVERS) AS TOTAL_CUSTOMERS,
    SUM(GROSS_SALES_AED) AS GROSS_SALES, 
    SUM(NET_SALES_AED) AS NET_SALES, 
    SUM(DISCOUNTS_AED) AS DISCOUNT, 
    SUM(NET_REVENUE_AED) AS NET_REVENUE,
    SUM(AGGREGATOR_COMMISSION_AED) AS COMMISSION,
    SUM(SERVICE_CHARGE_AED) AS TOTAL_SERVICE_CHARGE,
    SUM(VAT_AED) AS TOTAL_VAT,
    SUM(FOOD_COST_AED) AS TOTAL_FOOD_cOST,
    AVG(AVG_PREP_MINUTES) AS AVG_PREP_MINUTE,
    AVG(AVG_REVIEW_SCORE) AS AVG_RATING,
    sum(net_revenue_aed)/sum(orders_count) AS AOV 
FROM CHANNEL_DAILY
GROUP BY ORDER_CHANNEL
ORDER BY ORDER_CHANNEL;


SELECT ORDER_CHANNEL, LEFT(BUSINESS_MONTH,4) AS YEAR_, RIGHT(BUSINESS_MONTH,2) AS MONTH_,
    SUM(NET_REVENUE_AED) AS NET_REVENUE,
    LAG(SUM(NET_REVENUE_AED)) OVER(PARTITION BY ORDER_CHANNEL ORDER BY BUSINESS_MONTH) AS Prev_month_revenue,
    ROUND((SUM(NET_REVENUE_AED)-LAG(SUM(NET_REVENUE_AED)) OVER(PARTITION BY ORDER_CHANNEL ORDER BY BUSINESS_MONTH))/LAG(SUM(NET_REVENUE_AED)) OVER(PARTITION BY ORDER_CHANNEL ORDER BY BUSINESS_MONTH) * 100,2) AS MOM_REVENUE_GROWTH_PCT,
    SUM(ORDERS_COUNT) AS TOTAL_ORDERS,
    LAG(SUM(ORDERS_COUNT)) OVER(PARTITION BY ORDER_CHANNEL ORDER BY BUSINESS_MONTH) AS Prev_month_Orders,
    ROUND((SUM(ORDERS_COUNT)-LAG(SUM(ORDERS_COUNT)) OVER(PARTITION BY ORDER_CHANNEL ORDER BY BUSINESS_MONTH))/LAG(SUM(ORDERS_COUNT)) OVER(PARTITION BY ORDER_CHANNEL ORDER BY BUSINESS_MONTH) * 100,2) AS MOM_ORDER_GROWTH_PCT

FROM CHANNEL_DAILY
GROUP BY ORDER_CHANNEL, LEFT(BUSINESS_MONTH,4), RIGHT(BUSINESS_MONTH,2),BUSINESS_MONTH;

''' PROFIT MARGIN''' 

SELECT 
    ROUND(
    (SUM(NET_REVENUE_AED) - SUM(FOOD_COST_AED))
    /SUM(NET_REVENUE_AED)  *100,2) 
    AS Gross_profit_pct
FROM CHANNEL_DAILY;

'''Weekly Avg distribution'''

SELECT 
    DAY_OF_WEEK,
    ROUND(AVG(ORDERS_COUNT),0) AS TOTAL_ORDERS,
    ROUND(AVG(COVERS),0) AS TOTAL_CUSTOMERS,
    ROUND(AVG(GROSS_SALES_AED),2) AS GROSS_SALES, 
    ROUND(AVG(NET_SALES_AED),2) AS NET_SALES, 
    ROUND(AVG(DISCOUNTS_AED),2) AS DISCOUNT, 
    ROUND(AVG(AGGREGATOR_COMMISSION_AED),2) AS COMMISSION,
    ROUND(AVG(SERVICE_CHARGE_AED),2) AS TOTAL_SERVICE_CHARGE,
    ROUND(AVG(NET_REVENUE_AED),2) AS NET_REVENUE

FROM CHANNEL_DAILY
GROUP BY DAY_OF_WEEK;


'''Monthly Sales Trend

Questions:

Which month had highest sales?
Which month had lowest sales?
Is revenue increasing or decreasing?
How are orders changing over time? '''


SELECT
    BUSINESS_MONTH,
    SUM(ORDERS_COUNT) AS TOTAL_ORDERS,
    SUM(NET_SALES_AED) AS NET_SALES,
    SUM(NET_REVENUE_AED) AS NET_REVENUE,
    SUM(FOOD_COST_AED) AS FOOD_COST
FROM UAE_RESTAURANT_DB.CLEAN.CHANNEL_DAILY
GROUP BY BUSINESS_MONTH
ORDER BY BUSINESS_MONTH;




'''Highest sale - month year wise'''
SELECT BUSINESS_MONTH,NET_SALES FROM (
    SELECT BUSINESS_MONTH,
        LEFT(BUSINESS_MONTH, 4) AS YEAR_,
        SUM(NET_SALES_AED) AS NET_SALES,
        RANK() OVER(PARTITION BY  LEFT(BUSINESS_MONTH, 4) ORDER BY SUM(NET_REVENUE_AED) DESC) AS REVENUE_RANK
        
    FROM CHANNEL_DAILY
    GROUP BY BUSINESS_MONTH, LEFT(BUSINESS_MONTH, 4)
    ORDER BY REVENUE_RANK )
WHERE REVENUE_RANK =1;

'''Lowest sale - month year wise'''

SELECT BUSINESS_MONTH,NET_SALES FROM (
    SELECT BUSINESS_MONTH,
        LEFT(BUSINESS_MONTH, 4) AS YEAR_,
        SUM(NET_SALES_AED) AS NET_SALES,
        RANK() OVER(PARTITION BY  LEFT(BUSINESS_MONTH, 4) ORDER BY SUM(NET_REVENUE_AED) ASC) AS REVENUE_RANK
    FROM CHANNEL_DAILY
    GROUP BY BUSINESS_MONTH, LEFT(BUSINESS_MONTH, 4)
    ORDER BY REVENUE_RANK )
WHERE REVENUE_RANK =1;

'''Branch performance'''

SELECT b.branch_name,b.emirate,b.concept ,
    SUM(C.NET_REVENUE_AED) AS Net_Revenue,
    SUM(FOOD_COST_AED) AS Food_cost,
    SUM(C.NET_REVENUE_AED) - SUM(FOOD_COST_AED) AS Gross_profit
FROM BRANCHES AS B
RIGHT JOIN CHANNEL_DAILY AS C
ON B.BRANCH_ID = C.BRANCH_ID
GROUP BY b.branch_name,b.emirate,b.concept
ORDER BY Net_Revenue DESC;


SELECT * FROM DAILY_OPERATIONS;
SELECT * FROM BRANCHES;
SELECT * FROM ITEM_MONTHLY_SALES;
SELECT * FROM CHANNEL_DAILY;

'''Food Cost & Gross Margin Analysis'''

SELECT B.BRANCH_NAME, B.EMIRATE,B.AREA,B.CONCEPT,
    SUM(NET_REVENUE_AED) AS NET_REVENUE,
    SUM(FOOD_COST_AED) AS FOOD_COST,
    ROUND(SUM(FOOD_COST_AED)/SUM(NET_REVENUE_AED) * 100,2) AS FOOD_COST_PCT,
    sum(NET_REVENUE_AED) - SUM(FOOD_COST_AED) AS GROSS_MARGIN,
    ROUND((sum(NET_REVENUE_AED) - SUM(FOOD_COST_AED))/ SUM(NET_REVENUE_AED) * 100,2) AS GROSS_MARGIN_PCT

FROM DAILY_OPERATIONS AS D
LEFT JOIN BRANCHES AS B
ON D.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_NAME, B.EMIRATE,B.AREA,B.CONCEPT;


'''Labour, Waste & Prime Cost Analysis'''
SELECT * FROM DAILY_OPERATIONS;
SELECT * FROM BRANCHES;

SELECT B.BRANCH_NAME, B.EMIRATE,B.AREA,B.CONCEPT,
    SUM(FOOD_COST_AED) AS FOOD_COST,
    SUM(LABOUR_COST_AED) AS LABOUR_COST,
    ROUND(SUM(LABOUR_COST_AED)/SUM(NET_REVENUE_AED) * 100,2) AS LABOUR_COST_PCT,
    SUM(FOOD_COST_AED) + SUM(LABOUR_COST_AED) AS PRIME_COST,
    ROUND((SUM(FOOD_COST_AED) + SUM(LABOUR_COST_AED))/SUM(NET_REVENUE_AED) * 100,2) AS PRIME_COST_PCT,
    SUM(WASTE_COST_AED) AS WASTE_COST,
    ROUND(SUM(WASTE_COST_AED)/SUM(FOOD_COST_AED) *100,2)AS WASTE_PCT

FROM DAILY_OPERATIONS AS D
LEFT JOIN BRANCHES AS B
ON D.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_NAME, B.EMIRATE,B.AREA,B.CONCEPT;


'''NOT ACTIVE FOOD ITEMS IN MENU'''

SELECT * FROM MENU_ITEMS
WHERE IS_ACTIVE='FALSE';


SELECT M.MENU_CATEGORY, M.ITEM_NAME,
    SUM(QUANTITY_SOLD) AS TOTAL_QTY, 
    SUM(GROSS_SALES_AED) AS GROSS_SALES,
    SUM(FOOD_COST_AED) AS FOOD_COST,
    SUM(GROSS_MARGIN_AED) AS MARGIN,
    AVG(PREP_MINUTES) AS AVG_PREP_TIME

FROM ITEM_MONTHLY_SALES AS I
LEFT JOIN MENU_ITEMS AS M
ON I.ITEM_ID = M.ITEM_ID
GROUP BY M.MENU_CATEGORY, M.ITEM_NAME
ORDER BY MENU_CATEGORY,ITEM_NAME;

'''Revenue Contribution %'''
SELECT
    M.MENU_CATEGORY,
    SUM(GROSS_SALES_AED) AS GROSS_SALES,
    ROUND(SUM(GROSS_SALES_AED)/SUM(SUM(GROSS_SALES_AED)) OVER() * 100,2) AS REVENUE_CONTRIBUTION_PCT,
    ROUND(SUM(QUANTITY_SOLD)/ SUM(SUM(QUANTITY_SOLD)) OVER() * 100,2) AS QUANTITY_CONTRIBUTION_PCT


FROM ITEM_MONTHLY_SALES AS I
LEFT JOIN MENU_ITEMS AS M
ON I.ITEM_ID = M.ITEM_ID
GROUP BY M.MENU_CATEGORY;


SELECT MENU_CATEGORY,ITEM_NAME, MENU_PRICE_AED, ITEM_COST_AED,
MENU_PRICE_AED - ITEM_COST_AED AS MARGIN,
ROUND((MENU_PRICE_AED - ITEM_COST_AED)/MENU_PRICE_AED*100,2) AS MARGIN_PCT
FROM MENU_ITEMS;

SELECT * FROM MENU_ITEMS;


'''Is revenue increasing or decreasing?'''

SELECT *,
ROUND((x.NET_REVENUE - x.PREV_MONTH_SALES)/ x.PREV_MONTH_SALES * 100,2) AS MOM_GROWTH_PCT
    FROM (
        SELECT 
            LEFT(BUSINESS_MONTH,4) AS YEAR_,
            RIGHT(BUSINESS_MONTH,2) AS MONTH_,
            SUM(NET_REVENUE_AED) AS NET_REVENUE,
            LAG(SUM(NET_REVENUE_AED)) OVER(ORDER BY BUSINESS_MONTH ) AS PREV_MONTH_SALES
        
        FROM CHANNEL_DAILY
        GROUP BY LEFT(BUSINESS_MONTH,4),
            RIGHT(BUSINESS_MONTH,2), BUSINESS_MONTH
            ) AS  x;
            
'''How are orders changing over time? '''

SELECT *,
   ROUND((TOTAL_ORDERS - PREV_MONTH_ORDERS)/PREV_MONTH_ORDERS*100,2) AS MOM_ORDER_GROWTH_PCT
        FROM (
            SELECT ORDER_CHANNEL,
                LEFT(BUSINESS_MONTH,4) AS YEAR_,
                RIGHT(BUSINESS_MONTH,2) AS MONTH_,
                SUM(ORDERS_COUNT) AS TOTAL_ORDERS,
                LAG(SUM(ORDERS_COUNT)) OVER(PARTITION BY ORDER_CHANNEL ORDER BY BUSINESS_MONTH) AS PREV_MONTH_ORDERS
            
            FROM CHANNEL_DAILY AS C 
            GROUP BY ORDER_CHANNEL,
                LEFT(BUSINESS_MONTH,4),
                RIGHT(BUSINESS_MONTH,2),BUSINESS_MONTH
                )



'''Ranking Analysis

Top branches by revenue
Top channels by revenue
Top menu items by gross margin
Top categories by margin
Highest/lowest revenue months'''


SELECT B.BRANCH_NAME, B.EMIRATE, B.CONCEPT , C.ORDER_CHANNEL,
    LEFT(C.BUSINESS_MONTH,4) AS YEAR_,
    RIGHT(C.BUSINESS_MONTH,2) AS Month_,
    SUM(C.ORDERS_COUNT) AS TOTAL_ORDERS,
    SUM(C.NET_SALES_AED) AS TOTAL_SALES,
    SUM(C.NET_REVENUE_AED) AS TOTAL_REVENUE,
    SUM(C.NET_REVENUE_AED) - SUM(C.FOOD_COST_AED) AS GROSS_MARGIN,
    ROUND((SUM(NET_REVENUE_AED) - SUM(FOOD_COST_AED))/SUM(NET_REVENUE_AED) * 100,2) AS GROSS_MARGIN_PCT
FROM BRANCHES AS B
JOIN CHANNEL_DAILY AS C
ON B.BRANCH_ID = C.BRANCH_ID
GROUP BY B.BRANCH_NAME, B.EMIRATE, B.CONCEPT , C.ORDER_CHANNEL,LEFT(C.BUSINESS_MONTH,4),RIGHT(C.BUSINESS_MONTH,2)
ORDER BY GROSS_MARGIN_PCT DESC;


'''Ranking by monthly revenue'''

SELECT B.BRANCH_NAME,
    LEFT(C.BUSINESS_MONTH,4) AS YEAR_,
    RIGHT(C.BUSINESS_MONTH,2) AS Month_,
    SUM(C.ORDERS_COUNT) AS TOTAL_ORDERS,
    SUM(C.NET_SALES_AED) AS TOTAL_SALES,
    SUM(C.NET_REVENUE_AED) AS TOTAL_REVENUE,
    SUM(C.NET_REVENUE_AED) - SUM(C.FOOD_COST_AED) AS GROSS_MARGIN,
    ROUND((SUM(NET_REVENUE_AED) - SUM(FOOD_COST_AED))/SUM(NET_REVENUE_AED) * 100,2) AS GROSS_MARGIN_PCT,
    RANK() OVER(PARTITION BY LEFT(C.BUSINESS_MONTH,4),RIGHT(C.BUSINESS_MONTH,2)
    ORDER BY SUM(C.NET_REVENUE_AED) DESC) AS RANK_
FROM BRANCHES AS B
JOIN CHANNEL_DAILY AS C
ON B.BRANCH_ID = C.BRANCH_ID
GROUP BY B.BRANCH_NAME,LEFT(C.BUSINESS_MONTH,4),RIGHT(C.BUSINESS_MONTH,2)
ORDER BY YEAR_ ASC,
    MONTH_ ASC,
    RANK_ ASC;

'''Highest revenue Branch every month'''

SELECT * FROM 
    (
    SELECT B.BRANCH_NAME,
        LEFT(BUSINESS_MONTH,4)AS YEAR_,
        RIGHT(BUSINESS_MONTH,2) AS MONTH_,
        SUM(NET_REVENUE_AED) AS NET_REVENUE,
        RANK() OVER(PARTITION BY LEFT(BUSINESS_MONTH,4),RIGHT(C.BUSINESS_MONTH,2) ORDER BY SUM(NET_REVENUE_AED) DESC ) AS RANK_
    FROM CHANNEL_DAILY AS C
    LEFT JOIN BRANCHES AS B
    ON C.BRANCH_ID = B.BRANCH_ID
    GROUP BY B.BRANCH_NAME,
        LEFT(BUSINESS_MONTH,4),
        RIGHT(BUSINESS_MONTH,2)
    ) AS X
WHERE RANK_ = 1

'''Lowest revenue Branch every month'''

SELECT * FROM 
    (
    SELECT B.BRANCH_NAME,
        LEFT(BUSINESS_MONTH,4)AS YEAR_,
        RIGHT(BUSINESS_MONTH,2) AS MONTH_,
        SUM(NET_REVENUE_AED) AS NET_REVENUE,
        RANK() OVER(PARTITION BY LEFT(BUSINESS_MONTH,4),RIGHT(C.BUSINESS_MONTH,2) ORDER BY SUM(NET_REVENUE_AED) ASC ) AS RANK_
    FROM CHANNEL_DAILY AS C
    LEFT JOIN BRANCHES AS B
    ON C.BRANCH_ID = B.BRANCH_ID
    GROUP BY B.BRANCH_NAME,
        LEFT(BUSINESS_MONTH,4),
        RIGHT(BUSINESS_MONTH,2)
    ) AS X
WHERE RANK_ = 1

'''Highest revenue months'''

SELECT * FROM 
    (
    SELECT B.BRANCH_NAME,
        LEFT(BUSINESS_MONTH,4)AS YEAR_,
        RIGHT(BUSINESS_MONTH,2) AS MONTH_,
        SUM(NET_REVENUE_AED) AS NET_REVENUE,
        RANK() OVER(PARTITION BY LEFT(BUSINESS_MONTH,4) ORDER BY SUM(NET_REVENUE_AED) desc ) AS RANK_
    FROM CHANNEL_DAILY AS C
    LEFT JOIN BRANCHES AS B
    ON C.BRANCH_ID = B.BRANCH_ID
    GROUP BY B.BRANCH_NAME,
        LEFT(BUSINESS_MONTH,4),
        RIGHT(BUSINESS_MONTH,2)
    ) AS X
WHERE RANK_ = 1

'''lowest revenue months'''

SELECT * FROM 
    (
    SELECT B.BRANCH_NAME,
        LEFT(BUSINESS_MONTH,4)AS YEAR_,
        RIGHT(BUSINESS_MONTH,2) AS MONTH_,
        SUM(NET_REVENUE_AED) AS NET_REVENUE,
        RANK() OVER(PARTITION BY LEFT(BUSINESS_MONTH,4) ORDER BY SUM(NET_REVENUE_AED) ASC ) AS RANK_
    FROM CHANNEL_DAILY AS C
    LEFT JOIN BRANCHES AS B
    ON C.BRANCH_ID = B.BRANCH_ID
    GROUP BY B.BRANCH_NAME,
        LEFT(BUSINESS_MONTH,4),
        RIGHT(BUSINESS_MONTH,2)
    ) AS X
WHERE RANK_ = 1


'''Top items/categories by margin'''

SELECT ITEM_ID,ITEM_NAME,MENU_CATEGORY,
    MENU_PRICE_AED - ITEM_COST_AED AS MARGIN,
    ROUND((MENU_PRICE_AED - ITEM_COST_AED)/MENU_PRICE_AED * 100,2) AS MARGIN_PCT
FROM MENU_ITEMS AS M
ORDER BY MARGIN_PCT DESC;


'''DISCOUNT RATE'''

SELECT B.BRANCH_NAME ,
    SUM(DISCOUNTS_AED) AS TOTAL_DISCOUNT,
    ROUND(SUM(DISCOUNTS_AED)/SUM(NET_SALES_AED) * 100,2) AS DISCOUNT_PCT

FROM DAILY_OPERATIONS AS D 
JOIN BRANCHES AS B
ON D.BRANCH_ID = B.BRANCH_ID
GROUP BY B.BRANCH_NAME;

'''DISCOUNT RATE'''
SELECT 
    SUM(DISCOUNTS_AED) AS TOTAL_DISCOUNT,
    SUM(DISCOUNTS_AED)/SUM(NET_SALES_AED) * 100 AS DISCOUNT_PCT

FROM DAILY_OPERATIONS;

'''WEEKDAY VS WEEKEND'''
SELECT IS_WEEKEND,
    SUM(ORDERS_COUNT) AS ORDER_COUNT,
    SUM(NET_SALES_AED) AS NET_SALE,
    SUM(NET_REVENUE_AED) AS NET_REVENUE,
    SUM(FOOD_COST_AED) AS FOOD_COST,
    SUM(NET_REVENUE_AED) - SUM(FOOD_COST_AED) AS GROSS_MARGIN

FROM DAILY_OPERATIONS AS D
GROUP BY IS_WEEKEND;

'''ACTUAL PROFIT '''

SELECT * ,
    X.NET_PROFIT/X.NET_REVENUE * 100 AS MARGIN_
        FROM (
        
            SELECT B.BRANCH_NAME, LEFT(D.BUSINESS_MONTH, 4) AS YEAR_,
                SUM(D.NET_REVENUE_AED) AS NET_REVENUE,
                SUM(FOOD_COST_AED) AS FOOD_COST,
                SUM(D.LABOUR_COST_AED) AS LABOUR_COST,
                SUM(D.NET_REVENUE_AED) 
                    - SUM(D.FOOD_COST_AED) 
                    - SUM(D.LABOUR_COST_AED) 
                    - (B.MONTHLY_RENT_AED * COUNT(DISTINCT D.BUSINESS_MONTH)) AS NET_PROFIT
            FROM DAILY_OPERATIONS AS D
            LEFT JOIN BRANCHES AS B
            ON B.BRANCH_ID = D.BRANCH_ID
            GROUP BY B.BRANCH_NAME, B.MONTHLY_RENT_AED, LEFT(D.BUSINESS_MONTH, 4)
            ORDER BY YEAR_ ) as X 
    

        
SELECT * FROM BRANCHES

